mmngr_lib: mmngr: Fix warning in TP
Fix below warning when change to use new build environment.
(i.e GCC 5.1 and libc 2.22)

main.c:424:10: warning: implicit declaration of function 'strtoul'
[-Wimplicit-function-declaration]
   size = strtoul(argv[1], NULL, 0);
          ^

Signed-off-by: Khiem Nguyen <khiem.nguyen.xt@rvc.renesas.com>